-- ===========================================================================
-- SUPABASE DDL SCHEMA FOR HR AI ASSISTANT (MULTI-TURN CHAT SESSIONS + PGVECTOR)
-- Paste and Run this SQL in your Supabase Dashboard:
-- https://supabase.com/dashboard/project/giwwiktvxwvtdasorpwj/sql/new
-- ===========================================================================

-- 1. ENABLE PGVECTOR EXTENSION
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. DROP EXISTING TABLES IF NEEDED
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS data_chat_messages CASCADE;
DROP TABLE IF EXISTS policy_chat_messages CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS policy_chunks CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS lecturers CASCADE;

-- ---------------------------------------------------------------------------
-- 3. TABLE: lecturers
-- ---------------------------------------------------------------------------
CREATE TABLE lecturers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    track TEXT NOT NULL,
    city TEXT NOT NULL,
    phone TEXT,
    national_id TEXT,
    email TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    experience_years INTEGER NOT NULL DEFAULT 0,
    skills JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 4. TABLE: policies (Document Metadata)
-- ---------------------------------------------------------------------------
CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    paragraphs_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 5. TABLE: policy_chunks (Vector Embeddings Store)
-- ---------------------------------------------------------------------------
CREATE TABLE policy_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id TEXT NOT NULL,
    doc_title TEXT NOT NULL,
    ref TEXT NOT NULL,
    text TEXT NOT NULL,
    embedding vector(384),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast vector similarity search using Cosine Distance
CREATE INDEX IF NOT EXISTS policy_chunks_embedding_idx 
ON policy_chunks USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- ---------------------------------------------------------------------------
-- 6. RPC FUNCTION: match_policy_chunks (Database Cosine Similarity Search)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_policy_chunks (
  query_embedding vector(384),
  match_threshold float DEFAULT 0.2,
  match_count int DEFAULT 3
)
RETURNS TABLE (
  id bigint,
  doc_id text,
  doc_title text,
  ref text,
  text text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    id,
    doc_id,
    doc_title,
    ref,
    text,
    1 - (policy_chunks.embedding <=> query_embedding) AS similarity
  FROM policy_chunks
  WHERE 1 - (policy_chunks.embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
$$;

-- ---------------------------------------------------------------------------
-- 7. TABLE: chat_sessions (Full Conversation Threads)
-- ---------------------------------------------------------------------------
CREATE TABLE chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL, -- 'data' or 'policy'
    title TEXT NOT NULL,
    messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ---------------------------------------------------------------------------
ALTER TABLE lecturers ENABLE ROW LEVEL SECURITY;
ALTER TABLE policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE policy_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;

-- Lecturers RLS Policies
CREATE POLICY "Allow public read on lecturers" ON lecturers FOR SELECT USING (true);
CREATE POLICY "Allow public insert on lecturers" ON lecturers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on lecturers" ON lecturers FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on lecturers" ON lecturers FOR DELETE USING (true);

-- Policies RLS Policies
CREATE POLICY "Allow public read on policies" ON policies FOR SELECT USING (true);
CREATE POLICY "Allow public insert on policies" ON policies FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on policies" ON policies FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on policies" ON policies FOR DELETE USING (true);

-- Policy Chunks RLS Policies
CREATE POLICY "Allow public read on policy_chunks" ON policy_chunks FOR SELECT USING (true);
CREATE POLICY "Allow public insert on policy_chunks" ON policy_chunks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on policy_chunks" ON policy_chunks FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on policy_chunks" ON policy_chunks FOR DELETE USING (true);

-- Chat Sessions RLS Policies
CREATE POLICY "Allow public read on chat_sessions" ON chat_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on chat_sessions" ON chat_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on chat_sessions" ON chat_sessions FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on chat_sessions" ON chat_sessions FOR DELETE USING (true);
